package agentclient

import (
	"context"
	"crypto/tls"
	"crypto/x509"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"controlplane/internal/agentproto"
	"controlplane/internal/agentruntime"
	"github.com/coder/websocket"
)

func TestAgentUsageReplayHandlesConfigRenewalBeforeAck(t *testing.T) {
	outbox, err := NewFileUsageOutbox(filepath.Join(t.TempDir(), "usage.json"))
	if err != nil {
		t.Fatal(err)
	}
	defer outbox.Close()
	batch := sampleUsageBatch()
	if err := outbox.Enqueue(batch); err != nil {
		t.Fatal(err)
	}
	usageDigest, _ := agentproto.UsageBatchDigest(batch)
	_, digest, _ := agentproto.CanonicalForwardConfig(nil)
	later := time.Now().Add(4 * time.Minute)
	result := make(chan agentproto.ConfigResult, 1)
	server := httptest.NewUnstartedServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		conn, err := websocket.Accept(w, r, nil)
		if err != nil {
			t.Error(err)
			return
		}
		defer conn.CloseNow()
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		read := func() agentproto.Envelope {
			_, raw, err := conn.Read(ctx)
			if err != nil {
				t.Error(err)
				return agentproto.Envelope{}
			}
			v, err := agentproto.Decode(raw)
			if err != nil {
				t.Error(err)
			}
			return v
		}
		send := func(kind agentproto.MessageType, payload any) {
			body, _ := json.Marshal(payload)
			frame, _ := agentproto.Encode(agentproto.Envelope{ProtocolVersion: 1, MessageID: batch.BatchID, NodeID: testNodeID, Type: kind, SentAt: time.Now(), Payload: body})
			if err := conn.Write(ctx, websocket.MessageText, frame); err != nil {
				t.Error(err)
			}
		}
		if read().Type != agentproto.TypeHello {
			t.Error("expected hello")
			return
		}
		send(agentproto.TypeConfigSnapshot, agentproto.ConfigSnapshot{Revision: 1, SHA256: digest, ValidUntil: time.Now().Add(time.Minute), ForwardConfig: []agentruntime.Rule{}})
		if read().Type != agentproto.TypeUsageBatch {
			t.Error("usage missing")
			return
		}
		send(agentproto.TypeConfigSnapshot, agentproto.ConfigSnapshot{Revision: 1, SHA256: digest, ValidUntil: later, ForwardConfig: []agentruntime.Rule{}})
		send(agentproto.TypeUsageAck, agentproto.UsageAck{BatchID: batch.BatchID, SHA256: usageDigest})
		frame := read()
		if frame.Type != agentproto.TypeConfigResult {
			t.Errorf("result type = %s", frame.Type)
			return
		}
		got, err := agentproto.DecodeConfigResult(frame.Payload)
		if err != nil {
			t.Error(err)
		}
		result <- got
		// Usage generated by a running runtime must flush without requiring a
		// reconnect or a new configuration snapshot.
		next := sampleUsageBatch()
		next.BatchID = "eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee"
		next.Reports[0].Sequence = 2
		next.Reports[0].UploadedBytes++
		if err := outbox.Enqueue(next); err != nil {
			t.Error(err)
			return
		}
		frame = read()
		if frame.Type != agentproto.TypeUsageBatch {
			t.Errorf("live usage type = %s", frame.Type)
			return
		}
		nextDigest, _ := agentproto.UsageBatchDigest(next)
		send(agentproto.TypeUsageAck, agentproto.UsageAck{BatchID: next.BatchID, SHA256: nextDigest})
		// Wait until the client durably removes the ACKed report before closing.
		for len(outbox.Pending()) > 0 && ctx.Err() == nil {
			time.Sleep(time.Millisecond)
		}
	}))
	server.TLS = &tls.Config{MinVersion: tls.VersionTLS13, ClientAuth: tls.RequireAnyClientCert}
	server.StartTLS()
	defer server.Close()
	roots := x509.NewCertPool()
	roots.AddCert(server.Certificate())
	state := &fakeStateStore{}
	client, err := New(Config{URL: "wss" + strings.TrimPrefix(server.URL, "https") + "/api/v1/agent/stream", NodeID: testNodeID, Version: "1.0", RootCAs: roots, Certificate: testClientCertificate(t), UsageOutbox: outbox}, func() Runtime { return &fakeRuntime{} }, state)
	if err != nil {
		t.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	_ = client.RunOnce(ctx)
	if len(outbox.Pending()) != 0 {
		t.Fatal("usage not acknowledged")
	}
	select {
	case got := <-result:
		if got.Status != "applied" {
			t.Fatalf("result = %+v", got)
		}
	case <-ctx.Done():
		t.Fatal("config result missing")
	}
	state.mu.Lock()
	defer state.mu.Unlock()
	if state.last.ValidUntil.Before(later.Add(-time.Second)) {
		t.Fatalf("lost renewed configuration lease: %s", state.last.ValidUntil)
	}
}
